FIXUP: GENIO: drm/mediatek: hdmi: fix uninit var in mtk_hdmi_get_i2s_ch_mapping"
This fixes build error caused by the following commit:

commit 635c7e42e5f4 ("GENIO: drm/mediatek: hdmi: fix uninit var
in mtk_hdmi_get_i2s_ch_mapping")

The build error message is:

error: redeclaration of 'FC' with no linkage

Change-Id: I522006927422e54d421a12e7b0d728ef49208d21
Signed-off-by: Pablo Sun <pablo.sun@mediatek.com>
Signed-off-by: Hsuan-Yu Lin <shane.lin@canonical.com>