ASoC: mediatek: mt8365: add missing EXPORT_SYMBOLs
Fixes the following build errors when mt8365 is configured as module:

ERROR: modpost: "mt8365_afe_channel_supported"
[sound/soc/mediatek/mt8365/mt8365-evk.ko] undefined!
ERROR: modpost: "mt8365_afe_rate_supported"
[sound/soc/mediatek/mt8365/mt8365-evk.ko] undefined!

Signed-off-by: Hsuan-Yu Lin <shane.lin@canonical.com>